"""init schema

Revision ID: 6f02c577518b
Revises: 
Create Date: 2026-10-02 13:15:14.470327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f02c577518b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('moodle_category_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_moodle_category_id'), 'categories', ['moodle_category_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('INSTRUCTOR', 'STUDENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='userstatus'), nullable=False),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('instructor_profiles',
    sa.Column('user_id', sa.String(length=22), nullable=False),
    sa.Column('teaching_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('content_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activity_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('additional_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('reviews',
    sa.Column('reviewer_id', sa.String(length=22), nullable=False),
    sa.Column('target_type', sa.Enum('COURSE_PLAN', 'CONTENT', 'ACTIVITY', name='review_target_type'), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'EDIT_REQUESTED', name='review_decision'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_target_id'), 'reviews', ['target_id'], unique=False)
    op.create_table('rps',
    sa.Column('owner_id', sa.String(length=22), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', name='rps_status'), nullable=False),
    sa.Column('source_markdown', sa.Text(), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rps_file_hash'), 'rps', ['file_hash'], unique=False)
    op.create_index(op.f('ix_rps_owner_id'), 'rps', ['owner_id'], unique=False)
    op.create_index(op.f('ix_rps_status'), 'rps', ['status'], unique=False)
    op.create_table('course',
    sa.Column('instructor_id', sa.String(length=22), nullable=False),
    sa.Column('rps_id', sa.String(length=22), nullable=False),
    sa.Column('category', sa.String(length=22), nullable=False),
    sa.Column('course_format', sa.String(length=255), nullable=False),
    sa.Column('sortorder', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=254), nullable=False),
    sa.Column('shortname', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='course_status'), nullable=False),
    sa.Column('moodle_course_id', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rps_id'], ['rps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_format'),
    sa.UniqueConstraint('shortname')
    )
    op.create_index(op.f('ix_course_instructor_id'), 'course', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_course_moodle_course_id'), 'course', ['moodle_course_id'], unique=False)
    op.create_table('rps_analyses',
    sa.Column('rps_id', sa.String(length=22), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('course_identity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learning_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('objectives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weekly_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('teaching_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assessments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.ForeignKeyConstraint(['rps_id'], ['rps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rps_analyses_rps_id'), 'rps_analyses', ['rps_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('course_id', sa.String(length=22), nullable=False),
    sa.Column('run_type', sa.Enum('ANALYSIS', 'PLANNING', 'GENERATION', 'VALIDATION', 'EXECUTION', 'VERIFICATION', name='agent_run_type'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'WAITING', 'RETRYING', 'FAILED', 'COMPLETED', name='agent_run_status'), nullable=False),
    sa.Column('current_stage', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('model_runtime', sa.String(length=255), nullable=True),
    sa.Column('input_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_course_id'), 'agent_runs', ['course_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('agent_events',
    sa.Column('agent_run_id', sa.String(length=22), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_agent_run_id'), 'agent_events', ['agent_run_id'], unique=False)
    op.create_table('course_plans',
    sa.Column('course_id', sa.String(length=22), nullable=False),
    sa.Column('rps_analysis_id', sa.String(length=22), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', name='course_plan_status'), nullable=False),
    sa.Column('plan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by_agent_run_id', sa.String(length=22), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['generated_by_agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['rps_analysis_id'], ['rps_analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'version', name='uq_course_plans_course_version')
    )
    op.create_index(op.f('ix_course_plans_course_id'), 'course_plans', ['course_id'], unique=False)
    op.create_table('moodle_executions',
    sa.Column('course_id', sa.String(length=22), nullable=False),
    sa.Column('agent_run_id', sa.String(length=22), nullable=False),
    sa.Column('operation', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('moodle_object_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'BLOCKED', 'RETRYING', name='moodle_execution_status'), nullable=False),
    sa.Column('request_reference', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moodle_executions_course_id'), 'moodle_executions', ['course_id'], unique=False)
    op.create_index(op.f('ix_moodle_executions_moodle_object_id'), 'moodle_executions', ['moodle_object_id'], unique=False)
    op.create_index(op.f('ix_moodle_executions_status'), 'moodle_executions', ['status'], unique=False)
    op.create_table('validation_results',
    sa.Column('agent_run_id', sa.String(length=22), nullable=False),
    sa.Column('target_type', sa.Enum('COURSE_PLAN', 'CONTENT', 'ACTIVITY', 'MOODLE_EXECUTION', name='validation_target_type'), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'PARTIAL', name='validation_status'), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_agent_run_id'), 'validation_results', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_validation_results_target_id'), 'validation_results', ['target_id'], unique=False)
    op.create_table('course_plan_weeks',
    sa.Column('course_plan_id', sa.String(length=22), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('learning_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_plan_id'], ['course_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_plan_id', 'week_number', name='uq_course_plan_weeks_plan_week')
    )
    op.create_index(op.f('ix_course_plan_weeks_course_plan_id'), 'course_plan_weeks', ['course_plan_id'], unique=False)
    op.create_table('verifications',
    sa.Column('course_id', sa.String(length=22), nullable=False),
    sa.Column('execution_id', sa.String(length=22), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'PARTIAL', 'FAIL', 'UNKNOWN', name='verification_status'), nullable=False),
    sa.Column('expected_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discrepancies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['moodle_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_course_id'), 'verifications', ['course_id'], unique=False)
    op.create_table('activities',
    sa.Column('course_plan_week_id', sa.String(length=22), nullable=False),
    sa.Column('type', sa.Enum('ASSIGNMENT', 'QUIZ', name='activity_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('activity_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'APPROVED', 'EXECUTED', name='activity_status'), nullable=False),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.ForeignKeyConstraint(['course_plan_week_id'], ['course_plan_weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_course_plan_week_id'), 'activities', ['course_plan_week_id'], unique=False)
    op.create_table('contents',
    sa.Column('course_plan_week_id', sa.String(length=22), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.Enum('LEARNING_MATERIAL', 'RESOURCE', name='content_type'), nullable=False),
    sa.Column('content_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', name='content_status'), nullable=False),
    sa.Column('generated_by_agent_run_id', sa.String(length=22), nullable=True),
    sa.Column('id', sa.String(length=22), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(id) = 22', name='ck_id_length'),
    sa.ForeignKeyConstraint(['course_plan_week_id'], ['course_plan_weeks.id'], ),
    sa.ForeignKeyConstraint(['generated_by_agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_course_plan_week_id'), 'contents', ['course_plan_week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_course_plan_week_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_activities_course_plan_week_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_verifications_course_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_course_plan_weeks_course_plan_id'), table_name='course_plan_weeks')
    op.drop_table('course_plan_weeks')
    op.drop_index(op.f('ix_validation_results_target_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_agent_run_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_moodle_executions_status'), table_name='moodle_executions')
    op.drop_index(op.f('ix_moodle_executions_moodle_object_id'), table_name='moodle_executions')
    op.drop_index(op.f('ix_moodle_executions_course_id'), table_name='moodle_executions')
    op.drop_table('moodle_executions')
    op.drop_index(op.f('ix_course_plans_course_id'), table_name='course_plans')
    op.drop_table('course_plans')
    op.drop_index(op.f('ix_agent_events_agent_run_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_course_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_rps_analyses_rps_id'), table_name='rps_analyses')
    op.drop_table('rps_analyses')
    op.drop_index(op.f('ix_course_moodle_course_id'), table_name='course')
    op.drop_index(op.f('ix_course_instructor_id'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_rps_status'), table_name='rps')
    op.drop_index(op.f('ix_rps_owner_id'), table_name='rps')
    op.drop_index(op.f('ix_rps_file_hash'), table_name='rps')
    op.drop_table('rps')
    op.drop_index(op.f('ix_reviews_target_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('instructor_profiles')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_moodle_category_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
