"""integrate into moodle

Revision ID: 86ab20d2f2a8
Revises: 6f02c577518b
Create Date: 2026-10-02 13:59:52.316919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ab20d2f2a8'
down_revision: Union[str, Sequence[str], None] = '6f02c577518b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moodle_executions', 'course_id',
               existing_type=sa.VARCHAR(length=22),
               nullable=True)
    op.alter_column('moodle_executions', 'target_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=22),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moodle_executions', 'target_id',
               existing_type=sa.String(length=22),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('moodle_executions', 'course_id',
               existing_type=sa.VARCHAR(length=22),
               nullable=False)
    # ### end Alembic commands ###
